language: node_js

node_js:
  - "node"

env:
  - NODE_ENV=acceptance

sudo: required

dist: trusty

notifications:
  slack: ora-cocoon:H6FqgNRimkmlwsdBA9TzUMLJ#git

script:
  - grunt jshint
  - npm run test-single-run
