language: node_js

node_js:
  - "node"

env:
  - NODE_ENV=acceptance

sudo: required

dist: trusty

notifications:
  slack: orateam:UDiRK1WaPwbU8uNtWHzqT5vw

script:
  - grunt jshint
  - npm run test-single-run
